# dev environment overrides
namespace: ghostcmd-apps

image:
  repository: ghcr.io/user/project
  tag: dev-latest
  pullSecret: ghcr-credentials

ingress:
  enabled: true
  host: dev.proj-6.apps.ghostcmd.com
